### PR TITLE
Update the releases.yaml for 20.10 release

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Update the releases.yaml for 20.10 release

## QA
- Open the demo
- Go to /download
- See that there is a 20.10 download option

## Issue / Card
Fixes https://github.com/canonical-web-and-design/cn.ubuntu.com/issues/450

## Screenshots
image

### CODE REVIEW

**Comment by zprood** [comment]
@anthonydillon Hi, I checked the 20.10 lifecycle support date, the date for desktop is right, but server is not. Can you help to update the "line 115" of index.html under "templates/download" as below:
From: <p>最新版本Ubuntu Server，拥有9个月安全维护更新，支持到2020年7月。</p>
To: <p>最新版本Ubuntu Server，Ubuntu {{ releases.latest.full_version }} 拥有9个月安全维护更新，支持到{{ releases.latest.eol }}年6月。</p>

Thanks.

**Comment by anthonydillon** [comment]
Thanks @zprood 👍

**Comment by zprood** [comment]
> Thanks @zprood 👍

Now it's ready. :D

**Review by pmahnke — APPROVED** [review]
looks good, can you create and issue to update the checksums?

**Comment by anthonydillon** [comment]
@zprood is PR is not ready to land yet. Please do not release the site until Ubuntu is released

**Comment by zprood** [comment]
@anthonydillon Yes, I have talked Peter that will skip the checksums part. BTW, I won't do the release because I don't know and don't the permission for deployment.

**Pull request merged**
