### PR TITLE
Webinar takeover and sign up page

### PR DESCRIPTION
**Pull request by zprood**
## Done

Webinar takeover and sign up page
Update takeovers list
Update index page

### CODE REVIEW

**Comment by zprood** [comment]
Please hold on the PR, need to update copy.

**Comment by SirSamTumless** [comment]
@zprood this now ready to be reviewed?

**Comment by zprood** [comment]
@SirSamTumless not yet, sales are reviewing the copy doc right now, I will update when they confirmed. 
Thanks in advance.

**Comment by zprood** [comment]
@SirSamTumless Hi Sam, I have updated the copy and the demo works well. Can you review the PR? If there's no problem, can you merge and live it today ? Because we're delayed. Sorry.

**Pull request merged**
