### PR TITLE
Add 20.04 takeover and engage page + image template

### PR DESCRIPTION
**Pull request by pmahnke**
## Done

Add 20.04 takeover and engage page + image template

## QA

1. download this branch
2. look at http://0.0.0.0:8010/ and http://0.0.0.0:8010/engage/ff-release-party
3. see that they look ok and match the [brief](https://docs.google.com/spreadsheets/d/1oZ95LrwJaQehseVvVrtiuLk_PvmEVuKIc5GAXmJyOpA/edit#gid=1271849439)

## Issue / Card

Fixes #7187

## Screenshots

image

### CODE REVIEW

**Comment by zprood** [comment]
@pmahnke Hi Peter, thank you. We decide use the live video stream page to gain the lead because there's a problem can't be solved and the user flow will break from web form to video stream page. 

So,  please help to remove the engage page(ff-release-party), and just use the content for takeover will be great: 
**Button text (CTA)**：获取Ubuntu 20.04 LTS (link address: /download)
**Link and text for 20.04 event**: 参加Ubuntu 20.04 LTS线上发布活动 (link address: https://live.polyv.cn/watch/1280807)

**Comment by deadlight** [comment]
@zprood I've just rebuilt the demo (see link above). Can you check the changes, please?

**Comment by pmahnke** [comment]
+1 once the lint issue is fixed.

**Comment by zprood** [comment]
> @zprood I've just rebuilt the demo (see link above). Can you check the changes, please?

Sure, all good. Just one place that the support cycle for server LTS is 5 years. Sorry I don't know to correct the content on github, so mark the words here( It's under "download/index.html--Server section"): 
**Current:**
Ubuntu服务器的长期支持版本将包含OpenStack，同样地安全更新也将支持至2023年4月，仅限64位平台。
**New:** 
Ubuntu服务器的长期支持版本将包含OpenStack，同样地安全更新也将支持至2025年4月，仅限64位平台。

Thanks for the great work. Cheers!

**Comment by deadlight** [comment]
@zprood I made that change and built a new demo ^

**Comment by zprood** [comment]
@deadlight Cool, now all set. Thank you again.

**Pull request merged**
