### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by zprood**
Update desktop sub-release download link

## Done

[List of work items including drive-bys]

## QA

[List of steps to QA the new features or prove the bug has been resolved]

## Issue / Card

[List of links to Github issues/bugs and cards if needed - e.g. `Fixes #1`]

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Review by anthonydillon — APPROVED** [review]
LGTM

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Could you add the new variable to the title of the section to please?

**Review by anthonydillon — CHANGES_REQUESTED** [review]
Done

**Review by anthonydillon — APPROVED** [review]

**Comment by zprood** [comment]
@anthonydillon Thank you.

**Pull request merged**
