### PR TITLE
Update the blog pagination pattern

### PR DESCRIPTION
**Pull request by anthonydillon**
## Done
Update the pagination mark up to match the new Vanilla classes.

## QA
- Open the demo
- Go to /blog
- Scroll to the bottom and see the pagination looks right
- Use the pagination and check its working as expected

## Screenshots
image

### CODE REVIEW

**Review by bethcollins92 — APPROVED** [review]
LGTM 🥇

**Comment by carkod** [comment]
@anthonydillon need rebasing

**Comment by bethcollins92** [comment]
@anthonydillon FYI this is ready to merge once the checks pass

**Comment by anthonydillon** [comment]
@bethcollins92 thanks

**Pull request merged**
