### PR TITLE
Add Download page and adjust the urls 

### PR DESCRIPTION
**Pull request by zprood**
## Done

- Add Download page
- Adjust the download page urls to /download
- Rename blog chinese translation into 博客

## Screenshots

[if relevant, include a screenshot]
download

### CODE REVIEW

**Comment by zprood** [comment]
@anthonydillon I created a dowload page and fix some urls from my forked repo, no errors right now. Can I merge it into my branch "site-update", then create PR and go for master branch.

**Comment by anthonydillon** [comment]
@zprood I am not sure what has happened here but there are a lot of commits and I only see the translation change. I think it would be best to checkout a new branch from master and cherrypick the commits you mean to commit and propose them directly to master.

**Comment by zprood** [comment]
Yes, I don't mean to merge it into master directly. Instead, this PR is for "site-update" branch which is you suggested I create.

**Comment by zprood** [comment]
Create a branch : #327 includes this PR changes.

**Comment by zprood** [comment]
close this PR

**Pull request closed without merging**
