### PR TITLE
Fix marketo form fields invalid

### PR DESCRIPTION
**Pull request by zprood**
## Done
//WP landing page change
Just notice that the previous version marketo form code doesn't work well. It can download directly without filling. Re-placed with marketo form directly.

### CODE REVIEW

**Comment by zprood** [comment]
@solazio Can you help to check the PR ? As the PR mentioned, I replace the marketo form embedded code directly to make sure the mechanism is right.

**Comment by solazio** [comment]
@zprood this doesn't look right. See image below.
Can you please detail what was not working well previously. Is there any other way to fix it?
image

**Comment by zprood** [comment]
image
Hi @solazio see the screenshot, it works for me. I checked the data on marketo, it turns out people can directly click download button to view the WP pdf and no need filling out the form. I have checked the another engage page(robot OS), that one works and it needs filling out form first. 
So I replace the form code from marketo embedded form code.

**Comment by solazio** [comment]
@caldav what's your view on this?

**Comment by caldav** [comment]
Found the issue on the form validation. The old form id is present on line 125:
 `$("#mktoForm_3346").validate({` , should be `$("#mktoForm_3446").validate({`

**Comment by zprood** [comment]
Thanks a lot @caldav

**Pull request merged**
