### PR TITLE
Add a new page and content update

### PR DESCRIPTION
**Pull request by zprood**
## Done

- Create a new overview page for products and services(/enterprise)
- Update the menu order(rename tab title and re-order) 
- Page content update

## QA
- [ ] /enterprise page look review(Design)

### CODE REVIEW

**Comment by anthonydillon** [comment]
@zprood is this ready for review? You have applied -1 labels?

**Comment by zprood** [comment]
> @zprood is this ready for review? You have applied -1 labels?
Hi @anthonydillon Yes, label -1 is about ready to review, right? Thanks.

**Comment by anthonydillon** [comment]
No -1 is for a failed review. Needed labels are for ready 👍

**Comment by zprood** [comment]
Thanks, updating the labels. :D

**Review by carkod — APPROVED** [review]

**Pull request merged**
